---
apiVersion: v1
kind: Service
metadata:
  name: carts
  namespace: { { .Values.namespace } }
  labels:
    name: carts
spec:
  ports:
    - port: 80
      targetPort: { { .Values.carts.containerPort } }
  selector:
    name: carts
  type: ClusterIP
