---
apiVersion: v1
kind: Service
metadata:
  name: orders-db
  namespace: { { .Values.namespace } }
  labels:
    name: orders-db
spec:
  type: ExternalName
  externalName: { { .Values.ordersdb.service.externalName } }
