---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: { { .Values.namespace } }
  labels:
    name: rabbitmq
spec:
  type: ExternalName
  externalName: { { .Values.rabbitmq.service.externalName } }
