# Default values for sock-shop.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: default

global:
  registry: ""

java:
  options: -Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom

istio:
  enabled: false

cartsdb:
  # image:
  #   repo: mongo
  #   tag: 4.4.0
  # resources:
  #   requests:
  #     cpu: 500m
  #     memory: 512Mi
  #   limits:
  #     cpu: 500m
  #     memory: 512Mi
  # persistentVolume:
  #   storageClass: ''
  #   size: 512Mi
  service:
    externalName: usermgmtdb.cxojydmxwly6.us-east-1.rds.amazonaws.com

carts:
  image:
    repo: weaveworksdemos/carts
    tag: 0.4.8
  containerPort: 80
  resources:
    limits:
      cpu: 300m
      memory: 2000Mi
    requests:
      cpu: 300m
      memory: 2000Mi
  service:
    type: ClusterIP

zipkin:
  image:
    repo: openzipkin/zipkin
    tag: 2.21
  resources:
    limits:
      cpu: 300m
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 300Mi
  enabled: false
  url: zipkin.zipkin.svc.cluster.local
