---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: { { .Values.namespace } }
  labels:
    name: catalogue
spec:
  ports:
    - port: 80
      targetPort: { { .Values.catalogue.containerPort } }
  selector:
    name: catalogue
