---
apiVersion: v1
kind: Service
metadata:
  name: user-db
  namespace: { { .Values.namespace } }
  labels:
    name: user-db
  # namespace: prod
spec:
  type: ExternalName
  externalName: { { .Values.userdb.service.externalName } }
