---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: { { .Values.namespace } }
  labels:
    name: user
spec:
  ports:
    - port: 80
      targetPort: { { .Values.user.containerPort } }
  selector:
    name: user
