---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: { { .Values.namespace } }
  labels:
    name: shipping
spec:
  ports:
    - port: 80
      targetPort: { { .Values.shipping.containerPort } }
  selector:
    name: shipping
